linters-settings:
  gofmt:
    simplify: true
  govet:
    check-shadowing: true

linters:
  disable-all: true
  enable:
    - gofmt
    - govet
    - staticcheck
    - gosimple
    - ineffassign
    - unused
    - errcheck

run:
  timeout: 5m
  skip-dirs:
    - vendor

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec