linters:
  disable-all: true
  enable:
    - gofmt
    - govet
    - staticcheck
    - gosimple
    - ineffassign
    - unused
    - errcheck

output:
  format: colored-line-number

issues:
  exclude-dirs:
    - vendor
  max-same-issues: 0
  exclude-use-default: false

run:
  timeout: 5m
  allow-parallel-runners: true
  modules-download-mode: readonly