name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write  # Explicitly grant write permission for releases

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for tags

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          check-latest: true

      - name: Install dependencies
        run: |
          go mod download
          go mod tidy

      - name: Build Binaries
        run: |
          # Ensure dependencies are available
          go mod verify
          
          # Linux ARM64
          GOOS=linux GOARCH=arm64 go build -v -o alpine-template_linux_arm64
          # Linux AMD64
          GOOS=linux GOARCH=amd64 go build -v -o alpine-template_linux_amd64
          # macOS ARM64
          GOOS=darwin GOARCH=arm64 go build -v -o alpine-template_darwin_arm64
          # macOS AMD64
          GOOS=darwin GOARCH=amd64 go build -v -o alpine-template_darwin_amd64

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            alpine-template_linux_arm64
            alpine-template_linux_amd64
            alpine-template_darwin_arm64
            alpine-template_darwin_amd64
          generate_release_notes: true
          token: ${{ secrets.GITHUB_TOKEN }}  # Explicitly specify token
          draft: false
          prerelease: false