name: Security

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 8 * * 1'  # Run every Monday at 08:00 UTC

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Install dependencies
        run: |
          go mod download
          go mod tidy

      - name: Run Gosec Security Scanner
        uses: securego/gosec@master
        env:
          GO111MODULE: on
        with:
          args: -exclude-dir=vendor ./...

      - name: Run govulncheck
        uses: golang/govulncheck-action@v1
        with:
          go-version-input: '1.23'
          check-latest: true